# Site settings
title:          whthrulvmrnt
description:    "Minimal Jekyll theme for storytellers"
baseurl:        
url:            "https://ltr0121.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X
google_fonts: "Nanum+Gothic:400,700"

# Author
author:
  name:         whthrulvmrnt
  url:          https://ltr0121.github.io
  email:        whthrulvmrnt@ruu.kr

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
